"""Add warehouse

Revision ID: 2e671d76da75
Revises: 
Create Date: 2023-12-31 15:01:06.407611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2e671d76da75'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('min_stock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.UniqueConstraint('warehouse_id', 'name', name='uix_warehouse_id_name'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ean_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('units', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.UniqueConstraint('ean_code', 'category_id', name='uix_ean_code_category_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Add an index for the foreign key in the product table
    op.create_index('ix_category_warehouse_id', 'category', ['warehouse_id'])
    op.create_index('ix_product_category_id', 'product', ['category_id'])


def downgrade() -> None:
    # Drop indexs
    op.drop_index('ix_category_warehouse_id', 'category')
    op.drop_index('ix_product_category_id', 'product')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('category')
    op.drop_table('warehouse')
    # ### end Alembic commands ###
